let productsDatabase = [
    {
        id: 1,
        brand: "Nike",
        name: "Nike Air Max Plus VII 'Kylian Mbappé'",
        category: "Sneakers",
        gender: "Nam",
        price: 5279000,
        oldPrice: 0,
        badge: "new",
        img: "hinhAnh/giayNam/airMaxKM.png",
        thumbnails: ["hinhAnh/giayNam/airMaxKM.png"],
        colors: []
    },
    {
        id: 2,
        brand: "Nike",
        name: "Nike Air Max Plus",
        category: "Sneakers",
        gender: "Nam",
        price: 2169000,
        oldPrice: 0,
        badge: "bestseller",
        img: "hinhAnh/giayNam/airMaxPlus.png",
        thumbnails: ["hinhAnh/giayNam/airMaxPlus.png"],
        colors: []
    },
    {
        id: 3,
        brand: "Nike",
        name: "Nike Astrograbber SE",
        category: "Classic",
        gender: "Nam",
        price: 3829000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNam/astrograbber.png",
        thumbnails: ["hinhAnh/giayNam/astrograbber.png"],
        colors: []
    },
    {
        id: 4,
        brand: "Nike",
        name: "Nike Killshot 2",
        category: "Classic",
        gender: "Nam",
        price: 2779000,
        oldPrice: 0,
        badge: "bestseller",
        img: "hinhAnh/giayNam/killshot2.png",
        thumbnails: ["hinhAnh/giayNam/killshot2.png"],
        colors: []
    },
    {
        id: 5,
        brand: "Onitsuka Tiger",
        name: "Serrano",
        category: "Lifestyle",
        gender: "Nữ",
        price: 2945000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNu/otSerrano.png",
        thumbnails: ["hinhAnh/giayNu/otSerrano.png"],
        colors: []
    },
    {
        id: 6,
        brand: "Adidas",
        name: "Dép Lightshift",
        category: "Dép",
        gender: "Nữ",
        price: 750000,
        oldPrice: 950000,
        badge: "sale",
        img: "hinhAnh/giayNu/lightshift.png",
        thumbnails: ["hinhAnh/giayNu/lightshift.png"],
        colors: []
    },
    {
        id: 7,
        brand: "Adidas",
        name: "Adidas Adizero EVO SL",
        category: "Running",
        gender: "Nam",
        price: 4000000,
        oldPrice: 0,
        badge: "new",
        img: "hinhAnh/giayNam/zerosl.png",
        thumbnails: ["hinhAnh/giayNam/zerosl.png"],
        colors: []
    },
    {
        id: 8,
        brand: "Birkenstock",
        name: "Birkenstock Arizona",
        category: "Dép",
        gender: "Nam",
        price: 3390000,
        oldPrice: 0,
        badge: "bestseller",
        img: "hinhAnh/giayNam/arizona.png",
        thumbnails: ["hinhAnh/giayNam/arizona.png"],
        colors: []
    },
    {
        id: 9,
        brand: "Nike",
        name: "Nike Cortez Leather",
        category: "Classic",
        gender: "Nữ",
        price: 2499000,
        oldPrice: 0,
        badge: "bestseller",
        img: "hinhAnh/giayNu/cotez-w.png",
        thumbnails: ["hinhAnh/giayNu/cotez-w.png"],
        colors: []
    },
    {
        id: 10,
        brand: "Nike",
        name: "Nike Air Force 1 '07",
        category: "Classic",
        gender: "Nữ",
        price: 2499000,
        oldPrice: 0,
        badge: "bestseller",
        img: "hinhAnh/giayNu/af1-w.png",
        thumbnails: ["hinhAnh/giayNu/af1-w.png"],
        colors: []
    },
    {
        id: 11,
        brand: "Nike",
        name: "Nike Air Jordan 1 Low",
        category: "Sneakers",
        gender: "Nữ",
        price: 2999000,
        oldPrice: 0,
        badge: "new",
        img: "hinhAnh/giayNu/aj1-w.png",
        thumbnails: ["hinhAnh/giayNu/aj1-w.png"],
        colors: []
    },
    {
        id: 12,
        brand: "Nike",
        name: "Nike Astrograbber Women",
        category: "Classic",
        gender: "Nữ",
        price: 2890000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNu/asto-w.png",
        thumbnails: ["hinhAnh/giayNu/asto-w.png"],
        colors: []
    },
    {
        id: 13,
        brand: "Nike",
        name: "Nike P-6000 Women",
        category: "Sneakers",
        gender: "Nữ",
        price: 3290000,
        oldPrice: 0,
        badge: "bestseller",
        img: "hinhAnh/giayNu/p-6k-w.png",
        thumbnails: ["hinhAnh/giayNu/p-6k-w.png"],
        colors: []
    },
    {
        id: 14,
        brand: "Nike",
        name: "Nike Pegasus 42 Women",
        category: "Running",
        gender: "Nữ",
        price: 3890000,
        oldPrice: 0,
        badge: "new",
        img: "hinhAnh/giayNu/pega42-w.png",
        thumbnails: ["hinhAnh/giayNu/pega42-w.png"],
        colors: []
    },
    {
        id: 15,
        brand: "Nike",
        name: "Nike SB Dunk Low Women",
        category: "Sneakers",
        gender: "Nữ",
        price: 3499000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNu/sb-w.png",
        thumbnails: ["hinhAnh/giayNu/sb-w.png"],
        colors: []
    },
    {
        id: 16,
        brand: "Nike",
        name: "Nike Vomero 18 Women",
        category: "Running",
        gender: "Nữ",
        price: 4100000,
        oldPrice: 0,
        badge: "new",
        img: "hinhAnh/giayNu/voremo18-w.png",
        thumbnails: ["hinhAnh/giayNu/voremo18-w.png"],
        colors: []
    },
    {
        id: 17,
        brand: "Nike",
        name: "Nike Winflo Women",
        category: "Running",
        gender: "Nữ",
        price: 2690000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNu/winflo-w.png",
        thumbnails: ["hinhAnh/giayNu/winflo-w.png"],
        colors: []
    },
    {
        id: 18,
        brand: "Nike",
        name: "Nike WNBA 30th Anniversary",
        category: "Sneakers",
        gender: "Nữ",
        price: 3690000,
        oldPrice: 0,
        badge: "limited",
        img: "hinhAnh/giayNu/wnba 30th - w.png",
        thumbnails: ["hinhAnh/giayNu/wnba 30th - w.png"],
        colors: []
    },
    {
        id: 19,
        brand: "Nike",
        name: "Nike Air Jordan 1",
        category: "Sneakers",
        gender: "Nam",
        price: 3590000,
        oldPrice: 0,
        badge: "bestseller",
        img: "hinhAnh/giayNam/aj1.png",
        thumbnails: ["hinhAnh/giayNam/aj1.png"],
        colors: []
    },
    {
        id: 20,
        brand: "Nike",
        name: "Nike Air Max Ishod",
        category: "Sneakers",
        gender: "Nam",
        price: 2990000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNam/amishod.png",
        thumbnails: ["hinhAnh/giayNam/amishod.png"],
        colors: []
    },
    {
        id: 21,
        brand: "Nike",
        name: "Nike Air Force 1 '07 LV8",
        category: "Classic",
        gender: "Nam",
        price: 3290000,
        oldPrice: 0,
        badge: "new",
        img: "hinhAnh/giayNam/lv8.png",
        thumbnails: ["hinhAnh/giayNam/lv8.png"],
        colors: []
    },
    {
        id: 22,
        brand: "Nike",
        name: "Nike Pegasus 42",
        category: "Running",
        gender: "Nam",
        price: 3890000,
        oldPrice: 0,
        badge: "new",
        img: "hinhAnh/giayNam/pega42.png",
        thumbnails: ["hinhAnh/giayNam/pega42.png"],
        colors: []
    },
    {
        id: 23,
        brand: "Nike",
        name: "Nike Zoom Rival Fly",
        category: "Running",
        gender: "Nam",
        price: 2590000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNam/rfly.png",
        thumbnails: ["hinhAnh/giayNam/rfly.png"],
        colors: []
    },
    {
        id: 24,
        brand: "Nike",
        name: "Nike Winflo 12",
        category: "Running",
        gender: "Nam",
        price: 2890000,
        oldPrice: 0,
        badge: "new",
        img: "hinhAnh/giayNam/winflo12.png",
        thumbnails: ["hinhAnh/giayNam/winflo12.png"],
        colors: []
    },
    {
        id: 25,
        brand: "Nike",
        name: "Nike Cirro Slide",
        category: "Dép",
        gender: "Unisex",
        price: 950000,
        oldPrice: 0,
        badge: "new",
        img: "hinhAnh/giayNam/cirro-ux.png",
        thumbnails: ["hinhAnh/giayNam/cirro-ux.png"],
        colors: []
    },
    {
        id: 26,
        brand: "Nike",
        name: "Nike Marina Flip",
        category: "Dép",
        gender: "Nam",
        price: 850000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNam/marina.png",
        thumbnails: ["hinhAnh/giayNam/marina.png"],
        colors: []
    },
    {
        id: 27,
        brand: "Nike",
        name: "Nike ISPA Mindbody",
        category: "Dép",
        gender: "Nam",
        price: 5290000,
        oldPrice: 0,
        badge: "limited",
        img: "hinhAnh/giayNam/mind001.png",
        thumbnails: ["hinhAnh/giayNam/mind001.png"],
        colors: []
    },
    {
        id: 28,
        brand: "Nike",
        name: "Nike Calm Mule Women",
        category: "Dép",
        gender: "Nữ",
        price: 1690000,
        oldPrice: 0,
        badge: "bestseller",
        img: "hinhAnh/giayNu/calm-w.png",
        thumbnails: ["hinhAnh/giayNu/calm-w.png"],
        colors: []
    },
    {
        id: 29,
        brand: "Nike",
        name: "Nike Modero Sandal Women",
        category: "Dép",
        gender: "Nữ",
        price: 1250000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNu/modero-w.png",
        thumbnails: ["hinhAnh/giayNu/modero-w.png"],
        colors: []
    },
    {
        id: 30,
        brand: "Nike",
        name: "Nike Air Rift Breathe Women",
        category: "Dép",
        gender: "Nữ",
        price: 2990000,
        oldPrice: 0,
        badge: "new",
        img: "hinhAnh/giayNu/riftbreathe-w.png",
        thumbnails: ["hinhAnh/giayNu/riftbreathe-w.png"],
        colors: []
    },
    {
        id: 31,
        brand: "Adidas",
        name: "Adidas Superstar Women",
        category: "Sneakers",
        gender: "Nữ",
        price: 2600000,
        oldPrice: 0,
        badge: "bestseller",
        img: "hinhAnh/giayNu/adi2-w.png",
        thumbnails: ["hinhAnh/giayNu/adi2-w.png"],
        colors: []
    },
    {
        id: 32,
        brand: "Adidas",
        name: "Adidas Forum Low Women",
        category: "Sneakers",
        gender: "Nữ",
        price: 2800000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNu/adi4-w.png",
        thumbnails: ["hinhAnh/giayNu/adi4-w.png"],
        colors: []
    },
    {
        id: 33,
        brand: "Adidas",
        name: "Adidas Gazelle Beige",
        category: "Sneakers",
        gender: "Nữ",
        price: 2900000,
        oldPrice: 0,
        badge: "new",
        img: "hinhAnh/giayNu/adi8-w.png",
        thumbnails: ["hinhAnh/giayNu/adi8-w.png"],
        colors: []
    },
    {
        id: 34,
        brand: "Adidas",
        name: "Adidas Campus Pink",
        category: "Sneakers",
        gender: "Nữ",
        price: 2750000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNu/adi9-w.png",
        thumbnails: ["hinhAnh/giayNu/adi9-w.png"],
        colors: []
    },
    {
        id: 35,
        brand: "Adidas",
        name: "Adidas Adizero Adios Pink",
        category: "Running",
        gender: "Nữ",
        price: 3500000,
        oldPrice: 0,
        badge: "new",
        img: "hinhAnh/giayNu/adi5-w.png",
        thumbnails: ["hinhAnh/giayNu/adi5-w.png"],
        colors: []
    },
    {
        id: 36,
        brand: "Adidas",
        name: "Adidas Ultraboost Light Women",
        category: "Running",
        gender: "Nữ",
        price: 4200000,
        oldPrice: 4800000,
        badge: "sale",
        img: "hinhAnh/giayNu/adi6-w.png",
        thumbnails: ["hinhAnh/giayNu/adi6-w.png"],
        colors: []
    },
    {
        id: 37,
        brand: "Adidas",
        name: "Adidas Duramo SL Women",
        category: "Running",
        gender: "Nữ",
        price: 1800000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNu/adi7-w.png",
        thumbnails: ["hinhAnh/giayNu/adi7-w.png"],
        colors: []
    },
    {
        id: 38,
        brand: "Adidas",
        name: "Adidas Samba Grey Women",
        category: "Classic",
        gender: "Nữ",
        price: 3200000,
        oldPrice: 0,
        badge: "bestseller",
        img: "hinhAnh/giayNu/adi3-w.png",
        thumbnails: ["hinhAnh/giayNu/adi3-w.png"],
        colors: []
    },
    {
        id: 39,
        brand: "Adidas",
        name: "Adidas Samba OG Green",
        category: "Classic",
        gender: "Nữ",
        price: 3200000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNu/adi10-w.png",
        thumbnails: ["hinhAnh/giayNu/adi10-w.png"],
        colors: []
    },
    {
        id: 40,
        brand: "Adidas",
        name: "Adidas Superstar Men",
        category: "Sneakers",
        gender: "Nam",
        price: 2600000,
        oldPrice: 0,
        badge: "bestseller",
        img: "hinhAnh/giayNam/adi1.png",
        thumbnails: ["hinhAnh/giayNam/adi1.png"],
        colors: []
    },
    {
        id: 41,
        brand: "Adidas",
        name: "Adidas Forum Low Men",
        category: "Sneakers",
        gender: "Nam",
        price: 2800000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNam/adi3.png",
        thumbnails: ["hinhAnh/giayNam/adi3.png"],
        colors: []
    },
    {
        id: 42,
        brand: "Adidas",
        name: "Adidas Campus 00s Blue",
        category: "Sneakers",
        gender: "Nam",
        price: 2900000,
        oldPrice: 0,
        badge: "new",
        img: "hinhAnh/giayNam/adi6.png",
        thumbnails: ["hinhAnh/giayNam/adi6.png"],
        colors: []
    },
    {
        id: 43,
        brand: "Adidas",
        name: "Adidas VL Court Men",
        category: "Sneakers",
        gender: "Nam",
        price: 1950000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNam/adi8.png",
        thumbnails: ["hinhAnh/giayNam/adi8.png"],
        colors: []
    },
    {
        id: 44,
        brand: "Adidas",
        name: "Adidas Boston 12 Men",
        category: "Running",
        gender: "Nam",
        price: 3800000,
        oldPrice: 0,
        badge: "new",
        img: "hinhAnh/giayNam/adi4.png",
        thumbnails: ["hinhAnh/giayNam/adi4.png"],
        colors: []
    },
    {
        id: 45,
        brand: "Adidas",
        name: "Adidas Adizero SL Red",
        category: "Running",
        gender: "Nam",
        price: 3200000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNam/adi5.png",
        thumbnails: ["hinhAnh/giayNam/adi5.png"],
        colors: []
    },
    {
        id: 46,
        brand: "Adidas",
        name: "Adidas Galaxy 6 Men",
        category: "Running",
        gender: "Nam",
        price: 1500000,
        oldPrice: 1800000,
        badge: "sale",
        img: "hinhAnh/giayNam/adi9.png",
        thumbnails: ["hinhAnh/giayNam/adi9.png"],
        colors: []
    },
    {
        id: 47,
        brand: "Adidas",
        name: "Adidas Stan Smith Men",
        category: "Classic",
        gender: "Nam",
        price: 2500000,
        oldPrice: 0,
        badge: "bestseller",
        img: "hinhAnh/giayNam/adi2.png",
        thumbnails: ["hinhAnh/giayNam/adi2.png"],
        colors: []
    },
    {
        id: 48,
        brand: "Adidas",
        name: "Adidas Gazelle Indoor Black",
        category: "Classic",
        gender: "Nam",
        price: 3100000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNam/adi7.png",
        thumbnails: ["hinhAnh/giayNam/adi7.png"],
        colors: []
    },
    {
        id: 49,
        brand: "Adidas",
        name: "Adidas Adilette Clog Men",
        category: "Dép",
        gender: "Nam",
        price: 1200000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNam/slide1.png",
        thumbnails: ["hinhAnh/giayNam/slide1.png"],
        colors: []
    },
    {
        id: 50,
        brand: "Adidas",
        name: "Adidas Adilette Slide Green",
        category: "Dép",
        gender: "Nam",
        price: 950000,
        oldPrice: 0,
        badge: "new",
        img: "hinhAnh/giayNam/slide2.png",
        thumbnails: ["hinhAnh/giayNam/slide2.png"],
        colors: []
    },
    {
        id: 51,
        brand: "Adidas",
        name: "Adidas Adilette Aqua Blue",
        category: "Dép",
        gender: "Nam",
        price: 750000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNam/slide3.png",
        thumbnails: ["hinhAnh/giayNam/slide3.png"],
        colors: []
    },
    {
        id: 52,
        brand: "Adidas",
        name: "Adidas Adilette Slide Black",
        category: "Dép",
        gender: "Nam",
        price: 950000,
        oldPrice: 1200000,
        badge: "sale",
        img: "hinhAnh/giayNam/slide4.png",
        thumbnails: ["hinhAnh/giayNam/slide4.png"],
        colors: []
    },
    {
        id: 53,
        brand: "Adidas",
        name: "Adidas Adilette 22 Desert Sand",
        category: "Dép",
        gender: "Nam",
        price: 1600000,
        oldPrice: 0,
        badge: "bestseller",
        img: "hinhAnh/giayNam/slide5.png",
        thumbnails: ["hinhAnh/giayNam/slide5.png"],
        colors: []
    },
    {
        id: 54,
        brand: "Adidas",
        name: "Adidas Adilette Slide White Women",
        category: "Dép",
        gender: "Nữ",
        price: 950000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNu/slide1-w.png",
        thumbnails: ["hinhAnh/giayNu/slide1-w.png"],
        colors: []
    },
    {
        id: 55,
        brand: "Adidas",
        name: "Adidas Yeezy Slide Bone Women",
        category: "Dép",
        gender: "Nữ",
        price: 2500000,
        oldPrice: 0,
        badge: "bestseller",
        img: "hinhAnh/giayNu/slide2-w.png",
        thumbnails: ["hinhAnh/giayNu/slide2-w.png"],
        colors: []
    },
    {
        id: 56,
        brand: "Adidas",
        name: "Adidas Adilette Slide Navy Women",
        category: "Dép",
        gender: "Nữ",
        price: 950000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNu/slide3-w.png",
        thumbnails: ["hinhAnh/giayNu/slide3-w.png"],
        colors: []
    },
    {
        id: 57,
        brand: "Adidas",
        name: "Adidas Yeezy Slide Earth Women",
        category: "Dép",
        gender: "Nữ",
        price: 2500000,
        oldPrice: 0,
        badge: "new",
        img: "hinhAnh/giayNu/slide4-w.png",
        thumbnails: ["hinhAnh/giayNu/slide4-w.png"],
        colors: []
    }
];