let productsDatabase = [
    {
        id: 1,
        brand: "Nike",
        name: "Nike Air Max Plus VII 'Kylian Mbappé'",
        category: "Sneakers",
        gender: "Nam",
        price: 5279000,
        oldPrice: 0,
        badge: "New Arrival",
        img: "hinhAnh/giayNam/airMaxKM.png",
        thumbnails: ["hinhAnh/giayNam/airMaxKM.png"]
    },
    {
        id: 2,
        brand: "Nike",
        name: "Nike Air Max Plus",
        category: "Sneakers",
        gender: "Nam",
        price: 2169000,
        oldPrice: 0,
        badge: "Best Seller",
        img: "hinhAnh/giayNam/airMaxPlus.png",
        thumbnails: ["hinhAnh/giayNam/airMaxPlus.png"]
    },
    {
        id: 3,
        brand: "Nike",
        name: "Nike Astrograbber SE",
        category: "Classic",
        gender: "Nam",
        price: 3829000,
        oldPrice: 0,
        badge: "Best Seller",
        img: "hinhAnh/giayNam/astrograbber.png",
        thumbnails: ["hinhAnh/giayNam/astrograbber.png"]
    },
    {
        id: 4,
        brand: "Nike",
        name: "Nike Killshot 2",
        category: "Classic",
        gender: "Nam",
        price: 2779000,
        oldPrice: 0,
        badge: "Best Seller",
        img: "hinhAnh/giayNam/killshot2.png",
        thumbnails: ["hinhAnh/giayNam/killshot2.png"]
    },
    {
        id: 5,
        brand: "Onitsuka Tiger",
        name: "Serrano",
        category: "Sneakers",
        gender: "Nữ",
        price: 2945000,
        oldPrice: 0,
        badge: "Sale Off",
        img: "hinhAnh/giayNu/otSerrano.png",
        thumbnails: ["hinhAnh/giayNu/otSerrano.png"]
    },
    {
        id: 6,
        brand: "Adidas",
        name: "Dép Lightshift",
        category: "Dép",
        gender: "Nữ",
        price: 750000,
        oldPrice: 950000,
        badge: "Sale Off",
        img: "hinhAnh/giayNu/lightshift.png",
        thumbnails: ["hinhAnh/giayNu/lightshift.png"]
    },
    {
        id: 7,
        brand: "Adidas",
        name: "Adidas Adizero EVO SL",
        category: "Running",
        gender: "Nam",
        price: 4000000,
        oldPrice: 0,
        badge: "New Arrival",
        img: "hinhAnh/giayNam/zerosl.png",
        thumbnails: ["hinhAnh/giayNam/zerosl.png"]
    },
    {
        id: 8,
        brand: "Birkenstock",
        name: "Birkenstock Arizona",
        category: "Dép",
        gender: "Nam",
        price: 3390000,
        oldPrice: 0,
        badge: "Best Seller",
        img: "hinhAnh/giayNam/arizona.png",
        thumbnails: ["hinhAnh/giayNam/arizona.png"]
    },
    {
        id: 9,
        brand: "Nike",
        name: "Nike Cortez Leather",
        category: "Classic",
        gender: "Nữ",
        price: 2499000,
        oldPrice: 0,
        badge: "Best Seller",
        img: "hinhAnh/giayNu/cotez-w.png",
        thumbnails: ["hinhAnh/giayNu/cotez-w.png"]
    },
    {
        id: 10,
        brand: "Nike",
        name: "Nike Air Force 1 '07",
        category: "Classic",
        gender: "Nữ",
        price: 2499000,
        oldPrice: 0,
        badge: "Best Seller",
        img: "hinhAnh/giayNu/af1-w.png",
        thumbnails: ["hinhAnh/giayNu/af1-w.png"]
    },
    {
        id: 11,
        brand: "Nike",
        name: "Nike Air Jordan 1 Low",
        category: "Sneakers",
        gender: "Nữ",
        price: 2999000,
        oldPrice: 0,
        badge: "New Arrival",
        img: "hinhAnh/giayNu/aj1-w.png",
        thumbnails: ["hinhAnh/giayNu/aj1-w.png"]
    },
    {
        id: 12,
        brand: "Nike",
        name: "Nike Astrograbber Women",
        category: "Classic",
        gender: "Nữ",
        price: 2890000,
        oldPrice: 0,
        badge: "Sale Off",
        img: "hinhAnh/giayNu/asto-w.png",
        thumbnails: ["hinhAnh/giayNu/asto-w.png"]
    },
    {
        id: 13,
        brand: "Nike",
        name: "Nike P-6000 Women",
        category: "Sneakers",
        gender: "Nữ",
        price: 3290000,
        oldPrice: 0,
        badge: "Best Seller",
        img: "hinhAnh/giayNu/p-6k-w.png",
        thumbnails: ["hinhAnh/giayNu/p-6k-w.png"]
    },
    {
        id: 14,
        brand: "Nike",
        name: "Nike Pegasus 42 Women",
        category: "Running",
        gender: "Nữ",
        price: 3890000,
        oldPrice: 0,
        badge: "New Arrival",
        img: "hinhAnh/giayNu/pega42-w.png",
        thumbnails: ["hinhAnh/giayNu/pega42-w.png"]
    },
    {
        id: 15,
        brand: "Nike",
        name: "Nike SB Dunk Low Women",
        category: "Sneakers",
        gender: "Nữ",
        price: 3499000,
        oldPrice: 0,
        badge: "Sale Off",
        img: "hinhAnh/giayNu/sb-w.png",
        thumbnails: ["hinhAnh/giayNu/sb-w.png"]
    },
    {
        id: 16,
        brand: "Nike",
        name: "Nike Vomero 18 Women",
        category: "Running",
        gender: "Nữ",
        price: 4100000,
        oldPrice: 0,
        badge: "New Arrival",
        img: "hinhAnh/giayNu/voremo18-w.png",
        thumbnails: ["hinhAnh/giayNu/voremo18-w.png"]
    },
    {
        id: 17,
        brand: "Nike",
        name: "Nike Winflo Women",
        category: "Running",
        gender: "Nữ",
        price: 2690000,
        oldPrice: 0,
        badge: "Sale Off",
        img: "hinhAnh/giayNu/winflo-w.png",
        thumbnails: ["hinhAnh/giayNu/winflo-w.png"]
    },
    {
        id: 18,
        brand: "Nike",
        name: "Nike WNBA 30th Anniversary",
        category: "Sneakers",
        gender: "Nữ",
        price: 3690000,
        oldPrice: 0,
        badge: "New Arrival",
        img: "hinhAnh/giayNu/wnba 30th - w.png",
        thumbnails: ["hinhAnh/giayNu/wnba 30th - w.png"]
    },
    {
        id: 19,
        brand: "Nike",
        name: "Nike Air Jordan 1",
        category: "Sneakers",
        gender: "Nam",
        price: 3590000,
        oldPrice: 0,
        badge: "Best Seller",
        img: "hinhAnh/giayNam/aj1.png",
        thumbnails: ["hinhAnh/giayNam/aj1.png"]
    },
    {
        id: 20,
        brand: "Nike",
        name: "Nike Air Max Ishod",
        category: "Sneakers",
        gender: "Nam",
        price: 2990000,
        oldPrice: 0,
        badge: "New Arrival",
        img: "hinhAnh/giayNam/amishod.png",
        thumbnails: ["hinhAnh/giayNam/amishod.png"]
    },
    {
        id: 21,
        brand: "Nike",
        name: "Nike Air Force 1 '07 LV8",
        category: "Classic",
        gender: "Nam",
        price: 3290000,
        oldPrice: 0,
        badge: "New Arrival",
        img: "hinhAnh/giayNam/lv8.png",
        thumbnails: ["hinhAnh/giayNam/lv8.png"]
    },
    {
        id: 22,
        brand: "Nike",
        name: "Nike Pegasus 42",
        category: "Running",
        gender: "Nam",
        price: 3890000,
        oldPrice: 0,
        badge: "New Arrival",
        img: "hinhAnh/giayNam/pega42.png",
        thumbnails: ["hinhAnh/giayNam/pega42.png"]
    },
    {
        id: 23,
        brand: "Nike",
        name: "Nike Zoom Rival Fly",
        category: "Running",
        gender: "Nam",
        price: 2590000,
        oldPrice: 0,
        badge: "Best Seller",
        img: "hinhAnh/giayNam/rfly.png",
        thumbnails: ["hinhAnh/giayNam/rfly.png"]
    },
    {
        id: 24,
        brand: "Nike",
        name: "Nike Winflo 12",
        category: "Running",
        gender: "Nam",
        price: 2890000,
        oldPrice: 0,
        badge: "New Arrival",
        img: "hinhAnh/giayNam/winflo12.png",
        thumbnails: ["hinhAnh/giayNam/winflo12.png"]
    },
    {
        id: 25,
        brand: "Nike",
        name: "Nike Cirro Slide",
        category: "Dép",
        gender: "Unisex",
        price: 950000,
        oldPrice: 0,
        badge: "New Arrival",
        img: "hinhAnh/giayNam/cirro-ux.png",
        thumbnails: ["hinhAnh/giayNam/cirro-ux.png"]
    },
    {
        id: 26,
        brand: "Nike",
        name: "Nike Marina Flip",
        category: "Dép",
        gender: "Nam",
        price: 850000,
        oldPrice: 0,
        badge: "Sale Off",
        img: "hinhAnh/giayNam/marina.png",
        thumbnails: ["hinhAnh/giayNam/marina.png"]
    },
    {
        id: 27,
        brand: "Nike",
        name: "Nike ISPA Mindbody",
        category: "Dép",
        gender: "Nam",
        price: 5290000,
        oldPrice: 0,
        badge: "New Arrival",
        img: "hinhAnh/giayNam/mind001.png",
        thumbnails: ["hinhAnh/giayNam/mind001.png"]
    },
    {
        id: 28,
        brand: "Nike",
        name: "Nike Calm Mule Women",
        category: "Dép",
        gender: "Nữ",
        price: 1690000,
        oldPrice: 0,
        badge: "Best Seller",
        img: "hinhAnh/giayNu/calm-w.png",
        thumbnails: ["hinhAnh/giayNu/calm-w.png"]
    },
    {
        id: 29,
        brand: "Nike",
        name: "Nike Modero Sandal Women",
        category: "Dép",
        gender: "Nữ",
        price: 1250000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNu/modero-w.png",
        thumbnails: ["hinhAnh/giayNu/modero-w.png"]
    },
    {
        id: 30,
        brand: "Nike",
        name: "Nike Air Rift Breathe Women",
        category: "Dép",
        gender: "Nữ",
        price: 2990000,
        oldPrice: 0,
        badge: "New Arrival",
        img: "hinhAnh/giayNu/riftbreathe-w.png",
        thumbnails: ["hinhAnh/giayNu/riftbreathe-w.png"]
    },
    {
        id: 31,
        brand: "Adidas",
        name: "Adidas Superstar Women",
        category: "Sneakers",
        gender: "Nữ",
        price: 2600000,
        oldPrice: 0,
        badge: "Best Seller",
        img: "hinhAnh/giayNu/adi2-w.png",
        thumbnails: ["hinhAnh/giayNu/adi2-w.png"]
    },
    {
        id: 32,
        brand: "Adidas",
        name: "Adidas Forum Low Women",
        category: "Sneakers",
        gender: "Nữ",
        price: 2800000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNu/adi4-w.png",
        thumbnails: ["hinhAnh/giayNu/adi4-w.png"]
    },
    {
        id: 33,
        brand: "Adidas",
        name: "Adidas Gazelle Beige",
        category: "Sneakers",
        gender: "Nữ",
        price: 2900000,
        oldPrice: 0,
        badge: "New Arrival",
        img: "hinhAnh/giayNu/adi8-w.png",
        thumbnails: ["hinhAnh/giayNu/adi8-w.png"]
    },
    {
        id: 34,
        brand: "Adidas",
        name: "Adidas Campus Pink",
        category: "Sneakers",
        gender: "Nữ",
        price: 2750000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNu/adi9-w.png",
        thumbnails: ["hinhAnh/giayNu/adi9-w.png"]
    },
    {
        id: 35,
        brand: "Adidas",
        name: "Adidas Adizero Adios Pink",
        category: "Running",
        gender: "Nữ",
        price: 3500000,
        oldPrice: 0,
        badge: "New Arrival",
        img: "hinhAnh/giayNu/adi5-w.png",
        thumbnails: ["hinhAnh/giayNu/adi5-w.png"]
    },
    {
        id: 36,
        brand: "Adidas",
        name: "Adidas Ultraboost Light Women",
        category: "Running",
        gender: "Nữ",
        price: 4200000,
        oldPrice: 4800000,
        badge: "Sale Off",
        img: "hinhAnh/giayNu/adi6-w.png",
        thumbnails: ["hinhAnh/giayNu/adi6-w.png"]
    },
    {
        id: 37,
        brand: "Adidas",
        name: "Adidas Duramo SL Women",
        category: "Running",
        gender: "Nữ",
        price: 1800000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNu/adi7-w.png",
        thumbnails: ["hinhAnh/giayNu/adi7-w.png"]
    },
    {
        id: 38,
        brand: "Adidas",
        name: "Adidas Samba Grey Women",
        category: "Classic",
        gender: "Nữ",
        price: 3200000,
        oldPrice: 0,
        badge: "Best Seller",
        img: "hinhAnh/giayNu/adi3-w.png",
        thumbnails: ["hinhAnh/giayNu/adi3-w.png"]
    },
    {
        id: 39,
        brand: "Adidas",
        name: "Adidas Samba OG Green",
        category: "Classic",
        gender: "Nữ",
        price: 3200000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNu/adi10-w.png",
        thumbnails: ["hinhAnh/giayNu/adi10-w.png"]
    },
    {
        id: 40,
        brand: "Adidas",
        name: "Adidas Superstar Men",
        category: "Sneakers",
        gender: "Nam",
        price: 2600000,
        oldPrice: 0,
        badge: "Best Seller",
        img: "hinhAnh/giayNam/adi1.png",
        thumbnails: ["hinhAnh/giayNam/adi1.png"]
    },
    {
        id: 41,
        brand: "Adidas",
        name: "Adidas Forum Low Men",
        category: "Sneakers",
        gender: "Nam",
        price: 2800000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNam/adi3.png",
        thumbnails: ["hinhAnh/giayNam/adi3.png"]
    },
    {
        id: 42,
        brand: "Adidas",
        name: "Adidas Campus 00s Blue",
        category: "Sneakers",
        gender: "Nam",
        price: 2900000,
        oldPrice: 0,
        badge: "New Arrival",
        img: "hinhAnh/giayNam/adi6.png",
        thumbnails: ["hinhAnh/giayNam/adi6.png"]
    },
    {
        id: 43,
        brand: "Adidas",
        name: "Adidas VL Court Men",
        category: "Sneakers",
        gender: "Nam",
        price: 1950000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNam/adi8.png",
        thumbnails: ["hinhAnh/giayNam/adi8.png"]
    },
    {
        id: 44,
        brand: "Adidas",
        name: "Adidas Boston 12 Men",
        category: "Running",
        gender: "Nam",
        price: 3800000,
        oldPrice: 0,
        badge: "New Arrival",
        img: "hinhAnh/giayNam/adi4.png",
        thumbnails: ["hinhAnh/giayNam/adi4.png"]
    },
    {
        id: 45,
        brand: "Adidas",
        name: "Adidas Hyperboost Edge",
        category: "Running",
        gender: "Nam",
        price: 3200000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNam/adi5.png",
        thumbnails: ["hinhAnh/giayNam/adi5.png"]
    },
    {
        id: 46,
        brand: "Adidas",
        name: "Adidas Galaxy 6 Men",
        category: "Running",
        gender: "Nam",
        price: 1500000,
        oldPrice: 1800000,
        badge: "Sale Off",
        img: "hinhAnh/giayNam/adi9.png",
        thumbnails: ["hinhAnh/giayNam/adi9.png"]
    },
    {
        id: 47,
        brand: "Adidas",
        name: "Adidas Stan Smith Men",
        category: "Classic",
        gender: "Nam",
        price: 2500000,
        oldPrice: 0,
        badge: "Best Seller",
        img: "hinhAnh/giayNam/adi2.png",
        thumbnails: ["hinhAnh/giayNam/adi2.png"]
    },
    {
        id: 48,
        brand: "Adidas",
        name: "Adidas Gazelle Indoor Black",
        category: "Classic",
        gender: "Nam",
        price: 3100000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNam/adi7.png",
        thumbnails: ["hinhAnh/giayNam/adi7.png"]
    },
    {
        id: 49,
        brand: "Adidas",
        name: "Adidas Adilette Clog Men",
        category: "Dép",
        gender: "Nam",
        price: 1200000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNam/slide1.png",
        thumbnails: ["hinhAnh/giayNam/slide1.png"]
    },
    {
        id: 50,
        brand: "Adidas",
        name: "Adidas Adilette Slide Green",
        category: "Dép",
        gender: "Nam",
        price: 950000,
        oldPrice: 0,
        badge: "New Arrival",
        img: "hinhAnh/giayNam/slide2.png",
        thumbnails: ["hinhAnh/giayNam/slide2.png"]
    },
    {
        id: 51,
        brand: "Adidas",
        name: "Adidas Adilette Aqua Blue",
        category: "Dép",
        gender: "Nam",
        price: 750000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNam/slide3.png",
        thumbnails: ["hinhAnh/giayNam/slide3.png"]
    },
    {
        id: 52,
        brand: "Adidas",
        name: "Adidas Adilette Slide Black",
        category: "Dép",
        gender: "Nam",
        price: 950000,
        oldPrice: 1200000,
        badge: "Sale Off",
        img: "hinhAnh/giayNam/slide4.png",
        thumbnails: ["hinhAnh/giayNam/slide4.png"]
    },
    {
        id: 53,
        brand: "Adidas",
        name: "Adidas Adilette 22 Desert Sand",
        category: "Dép",
        gender: "Nam",
        price: 1600000,
        oldPrice: 0,
        badge: "Best Seller",
        img: "hinhAnh/giayNam/slide5.png",
        thumbnails: ["hinhAnh/giayNam/slide5.png"]
    },
    {
        id: 54,
        brand: "Adidas",
        name: "Adidas Adilette Slide White Women",
        category: "Dép",
        gender: "Nữ",
        price: 950000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNu/slide1-w.png",
        thumbnails: ["hinhAnh/giayNu/slide1-w.png"]
    },
    {
        id: 55,
        brand: "Adidas",
        name: "Adidas Yeezy Slide Bone Women",
        category: "Dép",
        gender: "Nữ",
        price: 2500000,
        oldPrice: 0,
        badge: "Best Seller",
        img: "hinhAnh/giayNu/slide2-w.png",
        thumbnails: ["hinhAnh/giayNu/slide2-w.png"]
    },
    {
        id: 56,
        brand: "Adidas",
        name: "Adidas Adilette Slide Navy Women",
        category: "Dép",
        gender: "Nữ",
        price: 950000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNu/slide3-w.png",
        thumbnails: ["hinhAnh/giayNu/slide3-w.png"]
    },
    {
        id: 57,
        brand: "Adidas",
        name: "Adidas Yeezy Slide Earth Women",
        category: "Dép",
        gender: "Nữ",
        price: 2500000,
        oldPrice: 0,
        badge: "New Arrival",
        img: "hinhAnh/giayNu/slide4-w.png",
        thumbnails: ["hinhAnh/giayNu/slide4-w.png"]
    },
    {
        id: 58,
        brand: "Puma",
        name: "Puma Deviate Nitro Women",
        category: "Running",
        gender: "Nữ",
        price: 3500000,
        oldPrice: 0,
        badge: "New Arrival",
        img: "hinhAnh/giayNu/pm1-w.jpg",
        thumbnails: ["hinhAnh/giayNu/pm1-w.jpg"]
    },
    {
        id: 59,
        brand: "Puma",
        name: "Puma Suede Classic Women",
        category: "Classic",
        gender: "Nữ",
        price: 2200000,
        oldPrice: 0,
        badge: "Best Seller",
        img: "hinhAnh/giayNu/pm2-w.jpg",
        thumbnails: ["hinhAnh/giayNu/pm2-w.jpg"]
    },
    {
        id: 60,
        brand: "Puma",
        name: "Puma RS-X White Women",
        category: "Sneakers",
        gender: "Nữ",
        price: 2800000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNu/pm3-w.jpg",
        thumbnails: ["hinhAnh/giayNu/pm3-w.jpg"]
    },
    {
        id: 61,
        brand: "Puma",
        name: "Puma MB.02 Flare Women",
        category: "Sneakers",
        gender: "Nữ",
        price: 3800000,
        oldPrice: 0,
        badge: "Best Seller",
        img: "hinhAnh/giayNu/pm4-w.jpg",
        thumbnails: ["hinhAnh/giayNu/pm4-w.jpg"]
    },
    {
        id: 62,
        brand: "Puma",
        name: "Puma RS-X Camo Women",
        category: "Sneakers",
        gender: "Nữ",
        price: 2900000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNu/pm5-w.jpg",
        thumbnails: ["hinhAnh/giayNu/pm5-w.jpg"]
    },
    {
        id: 63,
        brand: "Puma",
        name: "Puma Magnify Nitro Men",
        category: "Running",
        gender: "Nam",
        price: 3600000,
        oldPrice: 0,
        badge: "New Arrival",
        img: "hinhAnh/giayNam/pm1.jpg",
        thumbnails: ["hinhAnh/giayNam/pm1.jpg"]
    },
    {
        id: 64,
        brand: "Puma",
        name: "Puma Velocity Nitro Men",
        category: "Running",
        gender: "Nam",
        price: 3200000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNam/pm2.jpg",
        thumbnails: ["hinhAnh/giayNam/pm2.jpg"]
    },
    {
        id: 65,
        brand: "Puma",
        name: "Puma Deviate Nitro Yellow",
        category: "Running",
        gender: "Nam",
        price: 3500000,
        oldPrice: 3800000,
        badge: "Sale Off",
        img: "hinhAnh/giayNam/pm4.jpg",
        thumbnails: ["hinhAnh/giayNam/pm4.jpg"]
    },
    {
        id: 66,
        brand: "Puma",
        name: "Puma RS-X Triple Black",
        category: "Sneakers",
        gender: "Nam",
        price: 2800000,
        oldPrice: 0,
        badge: "Best Seller",
        img: "hinhAnh/giayNam/pm3.jpg",
        thumbnails: ["hinhAnh/giayNam/pm3.jpg"]
    },
    {
        id: 67,
        brand: "Puma",
        name: "Puma Slipstream Grey",
        category: "Sneakers",
        gender: "Nam",
        price: 2600000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNam/pm5.jpg",
        thumbnails: ["hinhAnh/giayNam/pm5.jpg"]
    },
    {
        id: 68,
        brand: "Puma",
        name: "Puma CA Pro White Red",
        category: "Sneakers",
        gender: "Nam",
        price: 2400000,
        oldPrice: 0,
        badge: "New Arrival",
        img: "hinhAnh/giayNam/pm7.jpg",
        thumbnails: ["hinhAnh/giayNam/pm7.jpg"]
    },
    {
        id: 69,
        brand: "Puma",
        name: "Puma RS-X Black Green",
        category: "Sneakers",
        gender: "Nam",
        price: 2900000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNam/pm8.jpg",
        thumbnails: ["hinhAnh/giayNam/pm8.jpg"]
    },
    {
        id: 70,
        brand: "Puma",
        name: "Puma Roma Black Men",
        category: "Classic",
        gender: "Nam",
        price: 1800000,
        oldPrice: 0,
        badge: "Best Seller",
        img: "hinhAnh/giayNam/pm6.jpg",
        thumbnails: ["hinhAnh/giayNam/pm6.jpg"]
    },
    {
        id: 71,
        brand: "Puma",
        name: "Puma Suede Grey Men",
        category: "Classic",
        gender: "Nam",
        price: 2200000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNam/pm9.jpg",
        thumbnails: ["hinhAnh/giayNam/pm9.jpg"]
    },
    {
        id: 72,
        brand: "Puma",
        name: "Puma Super Liga Blue",
        category: "Classic",
        gender: "Nam",
        price: 2100000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNam/pm10.jpg",
        thumbnails: ["hinhAnh/giayNam/pm10.jpg"]
    },
    {
        id: 73,
        brand: "New Balance",
        name: "New Balance 9060 Black Women",
        category: "Sneakers",
        gender: "Nữ",
        price: 3500000,
        oldPrice: 0,
        badge: "New Arrival",
        img: "hinhAnh/giayNu/nb1-w.jpg",
        thumbnails: ["hinhAnh/giayNu/nb1-w.jpg"]
    },
    {
        id: 74,
        brand: "New Balance",
        name: "New Balance Fresh Foam Women",
        category: "Running",
        gender: "Nữ",
        price: 3200000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNu/nb2-w.jpg",
        thumbnails: ["hinhAnh/giayNu/nb2-w.jpg"]
    },
    {
        id: 75,
        brand: "New Balance",
        name: "New Balance 530 Grey Women",
        category: "Running",
        gender: "Nữ",
        price: 2500000,
        oldPrice: 0,
        badge: "Best Seller",
        img: "hinhAnh/giayNu/nb3-w.jpg",
        thumbnails: ["hinhAnh/giayNu/nb3-w.jpg"]
    },
    {
        id: 76,
        brand: "New Balance",
        name: "New Balance 2002R Tan Women",
        category: "Sneakers",
        gender: "Nữ",
        price: 3600000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNu/nb4-w.jpg",
        thumbnails: ["hinhAnh/giayNu/nb4-w.jpg"]
    },
    {
        id: 77,
        brand: "New Balance",
        name: "New Balance 550 White Purple",
        category: "Classic",
        gender: "Nữ",
        price: 2900000,
        oldPrice: 0,
        badge: "New Arrival",
        img: "hinhAnh/giayNu/nb5-w.jpg",
        thumbnails: ["hinhAnh/giayNu/nb5-w.jpg"]
    },
    {
        id: 78,
        brand: "New Balance",
        name: "New Balance Slide Grey Women",
        category: "Dép",
        gender: "Nữ",
        price: 850000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNu/nbs1-w.jpg",
        thumbnails: ["hinhAnh/giayNu/nbs1-w.jpg"]
    },
    {
        id: 79,
        brand: "New Balance",
        name: "New Balance Slide Tan Women",
        category: "Dép",
        gender: "Nữ",
        price: 850000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNu/nbs2-w.jpg",
        thumbnails: ["hinhAnh/giayNu/nbs2-w.jpg"]
    },
    {
        id: 80,
        brand: "New Balance",
        name: "New Balance Clog Grey Women",
        category: "Dép",
        gender: "Nữ",
        price: 1200000,
        oldPrice: 0,
        badge: "New Arrival",
        img: "hinhAnh/giayNu/nbs3-w.jpg",
        thumbnails: ["hinhAnh/giayNu/nbs3-w.jpg"]
    },
    {
        id: 81,
        brand: "New Balance",
        name: "New Balance 1906R White Silver",
        category: "Running",
        gender: "Nam",
        price: 3600000,
        oldPrice: 0,
        badge: "New Arrival",
        img: "hinhAnh/giayNam/nb1.jpg",
        thumbnails: ["hinhAnh/giayNam/nb1.jpg"]
    },
    {
        id: 82,
        brand: "New Balance",
        name: "New Balance Fresh Foam Hierro",
        category: "Running",
        gender: "Nam",
        price: 3200000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNam/nb2.jpg",
        thumbnails: ["hinhAnh/giayNam/nb2.jpg"]
    },
    {
        id: 83,
        brand: "New Balance",
        name: "New Balance Rainier Boot",
        category: "Classic",
        gender: "Nam",
        price: 3900000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNam/nb3.jpg",
        thumbnails: ["hinhAnh/giayNam/nb3.jpg"]
    },
    {
        id: 84,
        brand: "New Balance",
        name: "New Balance 2002R Protection Pack",
        category: "Sneakers",
        gender: "Nam",
        price: 4200000,
        oldPrice: 0,
        badge: "Best Seller",
        img: "hinhAnh/giayNam/nb4.jpg",
        thumbnails: ["hinhAnh/giayNam/nb4.jpg"]
    },
    {
        id: 85,
        brand: "New Balance",
        name: "New Balance 530 White Silver",
        category: "Sneakers",
        gender: "Nam",
        price: 2500000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNam/nb5.jpg",
        thumbnails: ["hinhAnh/giayNam/nb5.jpg"]
    },
    {
        id: 86,
        brand: "New Balance",
        name: "New Balance Clog Black Men",
        category: "Dép",
        gender: "Nam",
        price: 1200000,
        oldPrice: 0,
        badge: "New Arrival",
        img: "hinhAnh/giayNam/nbs1.jpg",
        thumbnails: ["hinhAnh/giayNam/nbs1.jpg"]
    },
    {
        id: 87,
        brand: "New Balance",
        name: "New Balance Slide Black Men",
        category: "Dép",
        gender: "Nam",
        price: 850000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNam/nbs2.jpg",
        thumbnails: ["hinhAnh/giayNam/nbs2.jpg"]
    },
    {
        id: 88,
        brand: "Onitsuka Tiger",
        name: "Onitsuka Tiger Mexico 66 Navy Pink",
        category: "Classic",
        gender: "Nữ",
        price: 2900000,
        oldPrice: 0,
        badge: "New Arrival",
        img: "hinhAnh/giayNu/Screenshot 2026-04-18 140220.png",
        thumbnails: ["hinhAnh/giayNu/Screenshot 2026-04-18 140220.png"]
    },
    {
        id: 89,
        brand: "Onitsuka Tiger",
        name: "Onitsuka Tiger Mexico 66 Green",
        category: "Classic",
        gender: "Nữ",
        price: 2900000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNu/Screenshot 2026-04-18 140243.png",
        thumbnails: ["hinhAnh/giayNu/Screenshot 2026-04-18 140243.png"]
    },
    {
        id: 90,
        brand: "Onitsuka Tiger",
        name: "Onitsuka Tiger GSM Black",
        category: "Sneakers",
        gender: "Nữ",
        price: 3200000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNu/Screenshot 2026-04-18 140305.png",
        thumbnails: ["hinhAnh/giayNu/Screenshot 2026-04-18 140305.png"]
    },
    {
        id: 91,
        brand: "Onitsuka Tiger",
        name: "Onitsuka Tiger Mexico 66 Light Yellow",
        category: "Classic",
        gender: "Nữ",
        price: 2900000,
        oldPrice: 0,
        badge: "Best Seller",
        img: "hinhAnh/giayNu/Screenshot 2026-04-18 140340.png",
        thumbnails: ["hinhAnh/giayNu/Screenshot 2026-04-18 140340.png"]
    },
    {
        id: 92,
        brand: "Onitsuka Tiger",
        name: "Onitsuka Tiger Mexico 66 Yellow Black",
        category: "Classic",
        gender: "Nữ",
        price: 2900000,
        oldPrice: 3200000,
        badge: "Sale Off",
        img: "hinhAnh/giayNu/Screenshot 2026-04-18 140411.png",
        thumbnails: ["hinhAnh/giayNu/Screenshot 2026-04-18 140411.png"]
    },
    {
        id: 93,
        brand: "Onitsuka Tiger",
        name: "Onitsuka Tiger Tokuten Beige",
        category: "Sneakers",
        gender: "Nam",
        price: 2500000,
        oldPrice: 0,
        badge: "New Arrival",
        img: "hinhAnh/giayNam/Screenshot 2026-04-18 135942.png",
        thumbnails: ["hinhAnh/giayNam/Screenshot 2026-04-18 135942.png"]
    },
    {
        id: 94,
        brand: "Onitsuka Tiger",
        name: "Onitsuka Tiger Mexico 66 Brown",
        category: "Classic",
        gender: "Nam",
        price: 2900000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNam/Screenshot 2026-04-18 140014.png",
        thumbnails: ["hinhAnh/giayNam/Screenshot 2026-04-18 140014.png"]
    },
    {
        id: 95,
        brand: "Onitsuka Tiger",
        name: "Onitsuka Tiger GSM Triple Black",
        category: "Sneakers",
        gender: "Nam",
        price: 3200000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNam/Screenshot 2026-04-18 140034.png",
        thumbnails: ["hinhAnh/giayNam/Screenshot 2026-04-18 140034.png"]
    },
    {
        id: 96,
        brand: "Onitsuka Tiger",
        name: "Onitsuka Tiger Mexico 66 White Navy",
        category: "Classic",
        gender: "Nam",
        price: 2900000,
        oldPrice: 0,
        badge: "Best Seller",
        img: "hinhAnh/giayNam/Screenshot 2026-04-18 140129.png",
        thumbnails: ["hinhAnh/giayNam/Screenshot 2026-04-18 140129.png"]
    },
    {
        id: 97,
        brand: "Onitsuka Tiger",
        name: "Onitsuka Tiger Mexico 66 Black White",
        category: "Classic",
        gender: "Nam",
        price: 2900000,
        oldPrice: 0,
        badge: "New Arrival",
        img: "hinhAnh/giayNam/Screenshot 2026-04-18 140152.png",
        thumbnails: ["hinhAnh/giayNam/Screenshot 2026-04-18 140152.png"]
    },
    {
        id: 98,
        brand: "Birkenstock",
        name: "Birkenstock Boston Mocha",
        category: "Dép",
        gender: "Nam",
        price: 3600000,
        oldPrice: 0,
        badge: "Best Seller",
        img: "hinhAnh/giayNam/bk1.png",
        thumbnails: ["hinhAnh/giayNam/bk1.png"]
    },
    {
        id: 99,
        brand: "Birkenstock",
        name: "Birkenstock Milano BS",
        category: "Dép",
        gender: "Nam",
        price: 3200000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNam/bk2.png",
        thumbnails: ["hinhAnh/giayNam/bk2.png"]
    },
    {
        id: 100,
        brand: "Birkenstock",
        name: "Birkenstock Arizona Soft Footbed",
        category: "Dép",
        gender: "Nam",
        price: 3400000,
        oldPrice: 0,
        badge: "New Arrival",
        img: "hinhAnh/giayNam/bk3.png",
        thumbnails: ["hinhAnh/giayNam/bk3.png"]
    },
    {
        id: 101,
        brand: "Birkenstock",
        name: "Birkenstock Boston Suede Taupe",
        category: "Dép",
        gender: "Nam",
        price: 3800000,
        oldPrice: 0,
        badge: "Best Seller",
        img: "hinhAnh/giayNam/bk4.png",
        thumbnails: ["hinhAnh/giayNam/bk4.png"]
    },
    {
        id: 102,
        brand: "Birkenstock",
        name: "Birkenstock Arizona Suede Leather",
        category: "Dép",
        gender: "Nam",
        price: 3500000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNam/bk5.png",
        thumbnails: ["hinhAnh/giayNam/bk5.png"]
    },
    {
        id: 103,
        brand: "Birkenstock",
        name: "Birkenstock Boston Grey",
        category: "Dép",
        gender: "Nam",
        price: 3600000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNam/bk6.png",
        thumbnails: ["hinhAnh/giayNam/bk6.png"]
    },
    {
        id: 104,
        brand: "Birkenstock",
        name: "Birkenstock Boston Mink",
        category: "Dép",
        gender: "Nam",
        price: 3600000,
        oldPrice: 4000000,
        badge: "Sale Off",
        img: "hinhAnh/giayNam/bk7.png",
        thumbnails: ["hinhAnh/giayNam/bk7.png"]
    },
    {
        id: 105,
        brand: "Birkenstock",
        name: "Birkenstock Zermatt",
        category: "Dép",
        gender: "Nam",
        price: 2800000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNam/bk8.png",
        thumbnails: ["hinhAnh/giayNam/bk8.png"]
    },
    {
        id: 106,
        brand: "Birkenstock",
        name: "Birkenstock Milano EVA",
        category: "Dép",
        gender: "Nam",
        price: 2500000,
        oldPrice: 0,
        badge: "New Arrival",
        img: "hinhAnh/giayNam/bk9.png",
        thumbnails: ["hinhAnh/giayNam/bk9.png"]
    },
    {
        id: 107,
        brand: "Birkenstock",
        name: "Birkenstock Super Birki Men",
        category: "Dép",
        gender: "Nam",
        price: 2200000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNam/bk10.png",
        thumbnails: ["hinhAnh/giayNam/bk10.png"]
    },
    {
        id: 108,
        brand: "Birkenstock",
        name: "Birkenstock Boston Pink Women",
        category: "Dép",
        gender: "Nữ",
        price: 3600000,
        oldPrice: 0,
        badge: "New Arrival",
        img: "hinhAnh/giayNu/bk1-w.png",
        thumbnails: ["hinhAnh/giayNu/bk1-w.png"]
    },
    {
        id: 109,
        brand: "Birkenstock",
        name: "Birkenstock Boston Platform",
        category: "Dép",
        gender: "Nữ",
        price: 4200000,
        oldPrice: 0,
        badge: "Best Seller",
        img: "hinhAnh/giayNu/bk2-w.png",
        thumbnails: ["hinhAnh/giayNu/bk2-w.png"]
    },
    {
        id: 110,
        brand: "Birkenstock",
        name: "Birkenstock Boston Black Women",
        category: "Dép",
        gender: "Nữ",
        price: 3600000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNu/bk3-w.png",
        thumbnails: ["hinhAnh/giayNu/bk3-w.png"]
    },
    {
        id: 111,
        brand: "Birkenstock",
        name: "Birkenstock Boston Mocha Women",
        category: "Dép",
        gender: "Nữ",
        price: 3600000,
        oldPrice: 0,
        badge: "Best Seller",
        img: "hinhAnh/giayNu/bk4-w.png",
        thumbnails: ["hinhAnh/giayNu/bk4-w.png"]
    },
    {
        id: 112,
        brand: "Birkenstock",
        name: "Birkenstock Arizona Big Buckle",
        category: "Dép",
        gender: "Nữ",
        price: 3900000,
        oldPrice: 4500000,
        badge: "Sale Off",
        img: "hinhAnh/giayNu/bk5-w.png",
        thumbnails: ["hinhAnh/giayNu/bk5-w.png"]
    },
    {
        id: 113,
        brand: "Birkenstock",
        name: "Birkenstock Boston Grey Women",
        category: "Dép",
        gender: "Nữ",
        price: 3600000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNu/bk6-w.png",
        thumbnails: ["hinhAnh/giayNu/bk6-w.png"]
    },
    {
        id: 114,
        brand: "Birkenstock",
        name: "Birkenstock Boston Mink Women",
        category: "Dép",
        gender: "Nữ",
        price: 3600000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNu/bk7-w.png",
        thumbnails: ["hinhAnh/giayNu/bk7-w.png"]
    },
    {
        id: 115,
        brand: "Birkenstock",
        name: "Birkenstock Boston Corduroy",
        category: "Dép",
        gender: "Nữ",
        price: 3800000,
        oldPrice: 0,
        badge: "New Arrival",
        img: "hinhAnh/giayNu/bk8-w.png",
        thumbnails: ["hinhAnh/giayNu/bk8-w.png"]
    },
    {
        id: 116,
        brand: "Birkenstock",
        name: "Birkenstock Milano Women",
        category: "Dép",
        gender: "Nữ",
        price: 3200000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNu/bk9-w.png",
        thumbnails: ["hinhAnh/giayNu/bk9-w.png"]
    },
    {
        id: 117,
        brand: "Birkenstock",
        name: "Birkenstock Super Birki Women",
        category: "Dép",
        gender: "Nữ",
        price: 2200000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNu/bk10-w.png",
        thumbnails: ["hinhAnh/giayNu/bk10-w.png"]
    },
    {
        id: 118,
        brand: "Converse",
        name: "Converse Chuck 70 High Black",
        category: "Classic",
        gender: "Nam",
        price: 2200000,
        oldPrice: 0,
        badge: "Best Seller",
        img: "hinhAnh/giayNam/cv1.png",
        thumbnails: ["hinhAnh/giayNam/cv1.png"]
    },
    {
        id: 119,
        brand: "Converse",
        name: "Converse Chuck 70 Low Black",
        category: "Classic",
        gender: "Nam",
        price: 2000000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNam/cv2.png",
        thumbnails: ["hinhAnh/giayNam/cv2.png"]
    },
    {
        id: 120,
        brand: "Converse",
        name: "Converse Star Player 76 White",
        category: "Sneakers",
        gender: "Nam",
        price: 2300000,
        oldPrice: 0,
        badge: "New Arrival",
        img: "hinhAnh/giayNam/cv3.png",
        thumbnails: ["hinhAnh/giayNam/cv3.png"]
    },
    {
        id: 121,
        brand: "Converse",
        name: "Converse Chuck Taylor All Star High",
        category: "Classic",
        gender: "Nam",
        price: 1700000,
        oldPrice: 0,
        badge: "Best Seller",
        img: "hinhAnh/giayNam/cv4.png",
        thumbnails: ["hinhAnh/giayNam/cv4.png"]
    },
    {
        id: 122,
        brand: "Converse",
        name: "Converse Chuck 70 Low Red",
        category: "Sneakers",
        gender: "Nam",
        price: 2000000,
        oldPrice: 2400000,
        badge: "Sale Off",
        img: "hinhAnh/giayNam/cv5.png",
        thumbnails: ["hinhAnh/giayNam/cv5.png"]
    },
    {
        id: 123,
        brand: "Converse",
        name: "Converse One Star Pro",
        category: "Sneakers",
        gender: "Nam",
        price: 2500000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNam/cv6.png",
        thumbnails: ["hinhAnh/giayNam/cv6.png"]
    },
    {
        id: 124,
        brand: "Converse",
        name: "Converse Star Player 76 Green",
        category: "Sneakers",
        gender: "Nam",
        price: 2300000,
        oldPrice: 0,
        badge: "New Arrival",
        img: "hinhAnh/giayNam/cv7.png",
        thumbnails: ["hinhAnh/giayNam/cv7.png"]
    },
    {
        id: 125,
        brand: "Converse",
        name: "Converse Run Star Trainer Blue",
        category: "Sneakers",
        gender: "Nam",
        price: 2600000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNam/cv8.png",
        thumbnails: ["hinhAnh/giayNam/cv8.png"]
    },
    {
        id: 126,
        brand: "Converse",
        name: "Converse Chuck 70 High Grey",
        category: "Classic",
        gender: "Nam",
        price: 2200000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNam/cv9.png",
        thumbnails: ["hinhAnh/giayNam/cv9.png"]
    },
    {
        id: 127,
        brand: "Converse",
        name: "Converse Chuck Taylor High Grey",
        category: "Classic",
        gender: "Nam",
        price: 1700000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNam/cv10.png",
        thumbnails: ["hinhAnh/giayNam/cv10.png"]
    },
    {
        id: 128,
        brand: "Converse",
        name: "Converse Run Star Hike High",
        category: "Sneakers",
        gender: "Nữ",
        price: 2800000,
        oldPrice: 0,
        badge: "Best Seller",
        img: "hinhAnh/giayNu/cv1-w.png",
        thumbnails: ["hinhAnh/giayNu/cv1-w.png"]
    },
    {
        id: 129,
        brand: "Converse",
        name: "Converse Chuck 70 Low Parchment",
        category: "Classic",
        gender: "Nữ",
        price: 2000000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNu/cv2-w.png",
        thumbnails: ["hinhAnh/giayNu/cv2-w.png"]
    },
    {
        id: 130,
        brand: "Converse",
        name: "Converse Star Player 76 Beige",
        category: "Sneakers",
        gender: "Nữ",
        price: 2300000,
        oldPrice: 0,
        badge: "New Arrival",
        img: "hinhAnh/giayNu/cv3-w.png",
        thumbnails: ["hinhAnh/giayNu/cv3-w.png"]
    },
    {
        id: 131,
        brand: "Converse",
        name: "Converse Chuck Taylor High White",
        category: "Classic",
        gender: "Nữ",
        price: 1700000,
        oldPrice: 0,
        badge: "Best Seller",
        img: "hinhAnh/giayNu/cv4-w.png",
        thumbnails: ["hinhAnh/giayNu/cv4-w.png"]
    },
    {
        id: 132,
        brand: "Converse",
        name: "Converse Run Star Legacy CX",
        category: "Sneakers",
        gender: "Nữ",
        price: 3200000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNu/cv5-w.png",
        thumbnails: ["hinhAnh/giayNu/cv5-w.png"]
    },
    {
        id: 133,
        brand: "Converse",
        name: "Converse Chuck 70 Low Black Women",
        category: "Classic",
        gender: "Nữ",
        price: 2000000,
        oldPrice: 2400000,
        badge: "Sale Off",
        img: "hinhAnh/giayNu/cv6-w.png",
        thumbnails: ["hinhAnh/giayNu/cv6-w.png"]    
    },
    {
        id: 134,
        brand: "Converse",
        name: "Converse Chuck Taylor Lift Low",
        category: "Sneakers",
        gender: "Nữ",
        price: 2100000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNu/cv7-w.png",
        thumbnails: ["hinhAnh/giayNu/cv7-w.png"]
    },
    {
        id: 135,
        brand: "Converse",
        name: "Converse Chuck Taylor High Floral",
        category: "Classic",
        gender: "Nữ",
        price: 1900000,
        oldPrice: 0,
        badge: "New Arrival",
        img: "hinhAnh/giayNu/cv8-w.png",
        thumbnails: ["hinhAnh/giayNu/cv8-w.png"]
    },
    {
        id: 136,
        brand: "Converse",
        name: "Converse Run Star Hike Black",
        category: "Sneakers",
        gender: "Nữ",
        price: 2800000,
        oldPrice: 0,
        badge: "",
        img: "hinhAnh/giayNu/cv9-w.png",
        thumbnails: ["hinhAnh/giayNu/cv9-w.png"]
    },
    {
        id: 137,
        brand: "Converse",
        name: "Converse Mary Jane Beige",
        category: "Sneakers",
        gender: "Nữ",
        price: 2400000,
        oldPrice: 0,
        badge: "New Arrival",
        img: "hinhAnh/giayNu/cv10-w.png",
        thumbnails: ["hinhAnh/giayNu/cv10-w.png"]
    }
];